version: '3.7'

services:
  couchbase:
    image: couchbase/server:enterprise-7.0.0
    container_name: couchbase
    ports:
      - "8091-8094:8091-8094"  # Couchbase Web Console and REST/HTTP interface
      - "11210:11210"          # Couchbase Data
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=admin
      - COUCHBASE_ADMINISTRATOR_PASSWORD=password
      - COUCHBASE_BUCKET=test_db
      - COUCHBASE_RBAC_USERNAME=admin
      - COUCHBASE_RBAC_PASSWORD=password
      - COUCHBASE_BUCKET_TYPE=couchbase
      - COUCHBASE_BUCKET_RAMSIZE_MB=256
      - COUCHBASE_SERVICES=data,index,query,fts,eventing,analytics
    volumes:
      - couchbase_data:/opt/couchbase/var

volumes:
  couchbase_data:
