version: '3'
services:
  couchdb:
    image: couchdb
    container_name: my-couchdb
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: yourpassword
    volumes:
      - couchdb_data:/opt/couchdb/data

volumes:
  couchdb_data:
